### ISSUE TITLE
Hot to hide the hiden text in pdf after I turned it to Swf?

### ISSUE THREAD

**Issue by LiuHeZeng** [rpedroso/swftools#1]
I transfer the pdf to swt with swftools,the problem is when the transfor complished,the text hidden in pdf showd in swf?Do u guys have any suggestions ?Waitting online!

**Comment by zhengshuxin** [comment]
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00000000004d48eb in CharOutputDev::drawChar(GfxState_, double, double, double, double, double, double, unsigned int, int, unsigned int_, int) ()
#2  0x00000000004c7fbc in VectorGraphicOutputDev::drawChar(GfxState_, double, double, double, double, double, double, unsigned int, int, unsigned int_, int) ()
#3  0x0000000000492ccf in Gfx::doShowText(GString_) ()
#4  0x000000000049314f in Gfx::opShowSpaceText(Object_, int) ()
#5  0x000000000048ffcd in Gfx::execOp(Object_, Object_, int) ()
#6  0x0000000000490118 in Gfx::go(int) ()
#7  0x00000000004904a7 in Gfx::display(Object_, int) ()
#8  0x000000000048409e in Page::displaySlice(OutputDev_, double, double, int, int, int, int, int, int, int, int, Catalog_, int (_)(void_), void_) ()
#9  0x0000000000484267 in Page::display(OutputDev_, double, double, int, int, int, int, Catalog_, int (_)(void_), void_) ()
#10 0x00000000004599c0 in PDFDoc::displayPage(OutputDev_, int, double, double, int, int, int, int, int (_)(void_), void_) ()
#11 0x0000000000455b95 in render2(_gfxpage_, _gfxdevice_, int, int, int, int, int, int) ()
#12 0x0000000000455c7d in pdfpage_rendersection(_gfxpage_, _gfxdevice*, double, double, double, double, double, double) ()
#13 0x000000000040d2d7 in main ()
